const TranslateTitle = (title: string) => title
  .replace('Shingeki no Kyojin', '進撃の巨人')
  .replace('Death Note', 'デスノート')
  .replace('Fullmetal Alchemist: Brotherhood', '鋼の錬金術師 FULLMETAL ALCHEMIST')
  .replace('Sword Art Online', 'ソードアート・オンライン')
  .replace('One Punch Man', 'ワンパンマン')
  .replace('Boku no Hero Academia', '僕のヒーローアカデミア')
  .replace('Tokyo Ghoul', '東京喰種-トーキョーグール-')
  .replace('Code Geass: Hangyaku no Lelouch', 'コードギアス 反逆のルルーシュ')
  .replace('Kimi no Na wa.', '君の名は。')
  .replace('Toradora!', 'とらドラ！')
  .replace('Re:Zero kara Hajimeru Isekai Seikatsu', 'Re：ゼロから始める異世界生活')
  .replace('No Game No Life', 'ノーゲーム・ノーライフ')
  .replace('Mirai Nikki', '未来日記')
  .replace('Naruto', 'ナルト')
  .replace('Shippuuden', '疾風伝')
  .replace('Shigatsu wa Kimi no Uso', '四月は君の嘘')
  .replace('Noragami', 'ノラガミ')
  .replace('Ao no Exorcist', '青の祓魔師(エクソシスト)')
  .replace('Kimetsu no Yaiba', '鬼滅の刃')
  .replace('Boku dake ga Inai Machi', '僕だけがいない街')
  .replace('Koe no Katachi', '聲の形')
  .replace('Tate no Yuusha no Nariagari', '盾の勇者の成り上がり')
  .replace('Kobayashi-san Chi no Maid Dragon', '小林さんちのメイドラゴン')
  .replace('Akame ga Kill!', 'アカメが斬る!')
  .replace('Gintama Movie 2: Kanketsu-hen - Yorozuya yo Eien Nare', '劇場版 銀魂 完結篇 万事屋よ永遠なれ')
  .replace('Gintama: The Final', '銀魂 THE FINAL')
  .replace('Sen to Chihiro no Kamikakushi', '千と千尋の神隠し')
  .replace('Kizumonogatari III: Reiketsu-hen', '傷物語〈Ⅲ冷血篇〉')
  .replace('Made in Abyss Movie 3: Fukaki Tamashii no Reimei', ' 劇場版メイドインアビス 深き魂の黎明')
  .replace('Gintama', '銀魂')
  .replace('Ginga Eiyuu Densetsu','銀河英雄伝説')
  .replace('3-gatsu no Lion', '3月のライオン')
export default TranslateTitle